version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  upstream_a: 
    image: nginx:latest
    container_name: upsteam_a
    ports:
      - 80
  
  upstream_b: 
    image: nginx:latest
    container_name: upsteam_b
    ports:
      - 80
